name: bandgap-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - pytorch
  - xgboost
  - joblib
  - pip
  - pip:
    - matminer
    - pymatgen
    - scipy
